spring:
  cloud:
    gateway:
      routes: []
  config:
    import: optional:classpath:routes.yaml
{% if features.oauth2 %}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: {{ oidcIssuerUri }}
{% endif %}

logging:
  level:
    {{ basePackage }}: DEBUG
    org.springframework.cloud.gateway: TRACE
