apiVersion: v1
kind: Service
metadata:
  name: {{ projectName }}-storybook
  namespace: {{ k8sNamespace }}
spec:
  selector:
    app: {{ projectName }}-storybook
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
